local QBCore = exports['qb-core']:GetCoreObject()

local PlayerData = {}

Citizen.CreateThread(function()
    while QBCore == nil do
        TriggerEvent('QBCore:GetObject', function(obj) QBCore = obj end)
        Citizen.Wait(0)
    end
end)

RegisterNetEvent('QBCore:Client:OnPlayerLoaded')
AddEventHandler('QBCore:Client:OnPlayerLoaded', function(xPlayer)
    PlayerData = xPlayer
end)

--Xenons
RegisterNetEvent('customcarmods-xenon:onColorA')
AddEventHandler('customcarmods-xenon:onColorA', function()
  local playerVeh = GetPlayersLastVehicle()
  SetVehicleDoorOpen(playerVeh, 4, false, false)
  TaskStartScenarioInPlace(GetPlayerPed(-1), 'PROP_HUMAN_BUM_BIN', 0, true)
  QBCore.Functions.Progressbar("onColorA", "Installing", math.random(16000, 18000), false, true, {}, {}, {}, {}, function()
    ToggleVehicleMod(playerVeh, 22, true)
    SetVehicleXenonLightsColour(playerVeh, 2)
    Citizen.Wait(5200)
    SetVehicleDoorShut(playerVeh, 4, false)
  end, function()
    ClearPedTasksImmediately(GetPlayerPed(-1))
  end)
end)

RegisterNetEvent('customcarmods-xenon:onColorB')
AddEventHandler('customcarmods-xenon:onColorB', function()
  local playerVeh = GetPlayersLastVehicle()
  SetVehicleDoorOpen(playerVeh, 4, false, false)
  TaskStartScenarioInPlace(GetPlayerPed(-1), 'PROP_HUMAN_BUM_BIN', 0, true)
  QBCore.Functions.Progressbar("onColorB", "Installing", math.random(16000, 18000), false, true, {}, {}, {}, {}, function()
    ToggleVehicleMod(playerVeh, 22, true)
    SetVehicleXenonLightsColour(playerVeh, 2)
    Citizen.Wait(5200)
    SetVehicleDoorShut(playerVeh, 2, false)
  end, function()
    ClearPedTasksImmediately(GetPlayerPed(-1))
  end)
end)

RegisterNetEvent('customcarmods-xenon:onColorC')
AddEventHandler('customcarmods-xenon:onColorC', function()
  local playerVeh = GetPlayersLastVehicle()
  SetVehicleDoorOpen(playerVeh, 4, false, false)
  TaskStartScenarioInPlace(GetPlayerPed(-1), 'PROP_HUMAN_BUM_BIN', 0, true)
  QBCore.Functions.Progressbar("onColorC", "Installing", math.random(16000, 18000), false, true, {}, {}, {}, {}, function()
    ToggleVehicleMod(playerVeh, 22, true)
    SetVehicleXenonLightsColour(playerVeh, 2)
    Citizen.Wait(5200)
    SetVehicleDoorShut(playerVeh, 4, false)
  end, function()
    ClearPedTasksImmediately(GetPlayerPed(-1))
  end)
end)

RegisterNetEvent('customcarmods-xenon:onColorD')
AddEventHandler('customcarmods-xenon:onColorD', function()
  local playerVeh = GetPlayersLastVehicle()
  SetVehicleDoorOpen(playerVeh, 4, false, false)
  TaskStartScenarioInPlace(GetPlayerPed(-1), 'PROP_HUMAN_BUM_BIN', 0, true)
  QBCore.Functions.Progressbar("onColorD", "Installing", math.random(16000, 18000), false, true, {}, {}, {}, {}, function()
    ToggleVehicleMod(playerVeh, 22, true)
    SetVehicleXenonLightsColour(playerVeh, 2)
    Citizen.Wait(5200)
    SetVehicleDoorShut(playerVeh, 4, false)
  end, function()
    ClearPedTasksImmediately(GetPlayerPed(-1))
  end)
end)

RegisterNetEvent('customcarmods-xenon:onColorE')
AddEventHandler('customcarmods-xenon:onColorE', function()
  local playerVeh = GetPlayersLastVehicle()
  SetVehicleDoorOpen(playerVeh, 4, false, false)
  TaskStartScenarioInPlace(GetPlayerPed(-1), 'PROP_HUMAN_BUM_BIN', 0, true)
  QBCore.Functions.Progressbar("onColorE", "Installing", math.random(16000, 18000), false, true, {}, {}, {}, {}, function()
    ToggleVehicleMod(playerVeh, 22, true)
    SetVehicleXenonLightsColour(playerVeh, 2)
    Citizen.Wait(5200)
    SetVehicleDoorShut(playerVeh, 4, false)
  end, function()
    ClearPedTasksImmediately(GetPlayerPed(-1))
  end)
end)

RegisterNetEvent('customcarmods-xenon:onColorF')
AddEventHandler('customcarmods-xenon:onColorF', function()
  local playerVeh = GetPlayersLastVehicle()
  SetVehicleDoorOpen(playerVeh, 4, false, false)
  TaskStartScenarioInPlace(GetPlayerPed(-1), 'PROP_HUMAN_BUM_BIN', 0, true)
  QBCore.Functions.Progressbar("onColorF", "Installing", math.random(16000, 18000), false, true, {}, {}, {}, {}, function()
    ToggleVehicleMod(playerVeh, 22, true)
    SetVehicleXenonLightsColour(playerVeh, 2)
    Citizen.Wait(5200)
    SetVehicleDoorShut(playerVeh, 4, false)
  end, function()
    ClearPedTasksImmediately(GetPlayerPed(-1))
  end)
end)

RegisterNetEvent('customcarmods-xenon:onColorG')
AddEventHandler('customcarmods-xenon:onColorG', function()
  local playerVeh = GetPlayersLastVehicle()
  SetVehicleDoorOpen(playerVeh, 4, false, false)
  TaskStartScenarioInPlace(GetPlayerPed(-1), 'PROP_HUMAN_BUM_BIN', 0, true)
  QBCore.Functions.Progressbar("onColorG", "Installing", math.random(16000, 18000), false, true, {}, {}, {}, {}, function()
    ToggleVehicleMod(playerVeh, 22, true)
    SetVehicleXenonLightsColour(playerVeh, 2)
    Citizen.Wait(5200)
    SetVehicleDoorShut(playerVeh, 4, false)
  end, function()
    ClearPedTasksImmediately(GetPlayerPed(-1))
  end)
end)

RegisterNetEvent('customcarmods-xenon:onColorH')
AddEventHandler('customcarmods-xenon:onColorH', function()
  local playerVeh = GetPlayersLastVehicle()
  SetVehicleDoorOpen(playerVeh, 4, false, false)
  TaskStartScenarioInPlace(GetPlayerPed(-1), 'PROP_HUMAN_BUM_BIN', 0, true)
  QBCore.Functions.Progressbar("onColorH", "Installing", math.random(16000, 18000), false, true, {}, {}, {}, {}, function()
    ToggleVehicleMod(playerVeh, 22, true)
    SetVehicleXenonLightsColour(playerVeh, 2)
    Citizen.Wait(5200)
    SetVehicleDoorShut(playerVeh, 4, false)
  end, function()
    ClearPedTasksImmediately(GetPlayerPed(-1))
  end)
end)

RegisterNetEvent('customcarmods-xenon:onColorI')
AddEventHandler('customcarmods-xenon:onColorI', function()
  local playerVeh = GetPlayersLastVehicle()
  SetVehicleDoorOpen(playerVeh, 4, false, false)
  TaskStartScenarioInPlace(GetPlayerPed(-1), 'PROP_HUMAN_BUM_BIN', 0, true)
  QBCore.Functions.Progressbar("onColorI", "Installing", math.random(16000, 18000), false, true, {}, {}, {}, {}, function()
    ToggleVehicleMod(playerVeh, 22, true)
    SetVehicleXenonLightsColour(playerVeh, 2)
    Citizen.Wait(5200)
    SetVehicleDoorShut(playerVeh, 4, false)
  end, function()
    ClearPedTasksImmediately(GetPlayerPed(-1))
  end)
end)

RegisterNetEvent('customcarmods-xenon:onColorJ')
AddEventHandler('customcarmods-xenon:onColorJ', function()
  local playerVeh = GetPlayersLastVehicle()
  SetVehicleDoorOpen(playerVeh, 4, false, false)
  TaskStartScenarioInPlace(GetPlayerPed(-1), 'PROP_HUMAN_BUM_BIN', 0, true)
  QBCore.Functions.Progressbar("onColorJ", "Installing", math.random(16000, 18000), false, true, {}, {}, {}, {}, function()
    ToggleVehicleMod(playerVeh, 22, true)
    SetVehicleXenonLightsColour(playerVeh, 2)
    Citizen.Wait(5200)
    SetVehicleDoorShut(playerVeh, 4, false)
  end, function()
    ClearPedTasksImmediately(GetPlayerPed(-1))
  end)
end)

RegisterNetEvent('customcarmods-xenon:onColorK')
AddEventHandler('customcarmods-xenon:onColorK', function()
  local playerVeh = GetPlayersLastVehicle()
  SetVehicleDoorOpen(playerVeh, 4, false, false)
  TaskStartScenarioInPlace(GetPlayerPed(-1), 'PROP_HUMAN_BUM_BIN', 0, true)
  QBCore.Functions.Progressbar("onColorK", "Installing", math.random(16000, 18000), false, true, {}, {}, {}, {}, function()
    ToggleVehicleMod(playerVeh, 22, true)
    SetVehicleXenonLightsColour(playerVeh, 2)
    Citizen.Wait(5200)
    SetVehicleDoorShut(playerVeh, 4, false)
  end, function()
    ClearPedTasksImmediately(GetPlayerPed(-1))
  end)
end)

RegisterNetEvent('customcarmods-xenon:onColorL')
AddEventHandler('customcarmods-xenon:onColorL', function()
  local playerVeh = GetPlayersLastVehicle()
  SetVehicleDoorOpen(playerVeh, 4, false, false)
  TaskStartScenarioInPlace(GetPlayerPed(-1), 'PROP_HUMAN_BUM_BIN', 0, true)
  QBCore.Functions.Progressbar("onColorL", "Installing", math.random(16000, 18000), false, true, {}, {}, {}, {}, function()
    ToggleVehicleMod(playerVeh, 22, true)
    SetVehicleXenonLightsColour(playerVeh, 2)
    Citizen.Wait(5200)
    SetVehicleDoorShut(playerVeh, 4, false)
  end, function()
    ClearPedTasksImmediately(GetPlayerPed(-1))
  end)
end)

RegisterNetEvent('customcarmods-xenon:onColorM')
AddEventHandler('customcarmods-xenon:onColorM', function()
  local playerVeh = GetPlayersLastVehicle()
  SetVehicleDoorOpen(playerVeh, 4, false, false)
  TaskStartScenarioInPlace(GetPlayerPed(-1), 'PROP_HUMAN_BUM_BIN', 0, true)
  QBCore.Functions.Progressbar("onColorM", "Installing", math.random(16000, 18000), false, true, {}, {}, {}, {}, function()
    ToggleVehicleMod(playerVeh, 22, true)
    SetVehicleXenonLightsColour(playerVeh, 2)
    Citizen.Wait(5200)
    SetVehicleDoorShut(playerVeh, 4, false)
  end, function()
    ClearPedTasksImmediately(GetPlayerPed(-1))
  end)
end)

RegisterNetEvent('customcarmods-xenon:onColorN')
AddEventHandler('customcarmods-xenon:onColorN', function()
  local playerVeh = GetPlayersLastVehicle()
  SetVehicleDoorOpen(playerVeh, 4, false, false)
  TaskStartScenarioInPlace(GetPlayerPed(-1), 'PROP_HUMAN_BUM_BIN', 0, true)
  QBCore.Functions.Progressbar("onColorN", "Installing", math.random(16000, 18000), false, true, {}, {}, {}, {}, function()
    ToggleVehicleMod(playerVeh, 22, true)
    SetVehicleXenonLightsColour(playerVeh, 2)
    Citizen.Wait(5200)
    SetVehicleDoorShut(playerVeh, 4, false)
  end, function()
    ClearPedTasksImmediately(GetPlayerPed(-1))
  end)
end)
--Moteur
RegisterNetEvent('customcarmods-engine:engine1')
AddEventHandler('customcarmods-engine:engine1', function()
  local playerVeh = GetPlayersLastVehicle()
  ExecuteCommand( "raisecar")
  Citizen.Wait(1000)
  SetVehicleDoorOpen(playerVeh, 4, false, false)
  TaskStartScenarioInPlace(GetPlayerPed(-1), 'PROP_HUMAN_BUM_BIN', 0, true)
  QBCore.Functions.Progressbar("engine1", "Installing Basic Engine", math.random(16000, 18000), false, true, {}, {}, {}, {}, function()
    SetVehicleMod(playerVeh, 11, 0, true)
    Citizen.Wait(4500)
    SetVehicleDoorShut(playerVeh, 4, false)
  end, function()
    ClearPedTasksImmediately(GetPlayerPed(-1))
    ExecuteCommand( "lowercar")
  end)
end)

RegisterNetEvent('customcarmods-engine:engine2')
AddEventHandler('customcarmods-engine:engine2', function()
  local playerVeh = GetPlayersLastVehicle()
  ExecuteCommand( "raisecar")
  Citizen.Wait(1000)
  SetVehicleDoorOpen(playerVeh, 4, false, false)
  TaskStartScenarioInPlace(GetPlayerPed(-1), 'PROP_HUMAN_BUM_BIN', 0, true)
  QBCore.Functions.Progressbar("engine2", "Installing level 1 upgrade", math.random(16000, 18000), false, true, {}, {}, {}, {}, function()
    SetVehicleMod(playerVeh, 11, 0, true)
    Citizen.Wait(3500)
    SetVehicleDoorShut(playerVeh, 4, false)
  end, function()
    ClearPedTasksImmediately(GetPlayerPed(-1))
    ExecuteCommand( "lowercar")
  end)
end)

RegisterNetEvent('customcarmods-engine:engine3')
AddEventHandler('customcarmods-engine:engine3', function()
  local playerVeh = GetPlayersLastVehicle()
  ExecuteCommand( "raisecar")
  Citizen.Wait(1000)
  SetVehicleDoorOpen(playerVeh, 4, false, false)
  TaskStartScenarioInPlace(GetPlayerPed(-1), 'PROP_HUMAN_BUM_BIN', 0, true)
  QBCore.Functions.Progressbar("engine2", "Installing level 2 upgrade", math.random(16000, 18000), false, true, {}, {}, {}, {}, function()
    SetVehicleMod(playerVeh, 11, 0, true)
    Citizen.Wait(3500)
    SetVehicleDoorShut(playerVeh, 4, false)
  end, function()
    ClearPedTasksImmediately(GetPlayerPed(-1))
    ExecuteCommand( "lowercar")
  end)
end)

RegisterNetEvent('customcarmods-engine:engine4')
AddEventHandler('customcarmods-engine:engine4', function()
  local playerVeh = GetPlayersLastVehicle()
  ExecuteCommand( "raisecar")
  Citizen.Wait(1000)
  SetVehicleDoorOpen(playerVeh, 4, false, false)
  TaskStartScenarioInPlace(GetPlayerPed(-1), 'PROP_HUMAN_BUM_BIN', 0, true)
  QBCore.Functions.Progressbar("engine4", "Installing level 3 upgrade", math.random(16000, 18000), false, true, {}, {}, {}, {}, function()
    SetVehicleMod(playerVeh, 11, 0, true)
    Citizen.Wait(3500)
    SetVehicleDoorShut(playerVeh, 4, false)
  end, function()
    ClearPedTasksImmediately(GetPlayerPed(-1))
    ExecuteCommand( "lowercar")
  end)
end)

RegisterNetEvent('customcarmods-engine:engine5')
AddEventHandler('customcarmods-engine:engine5', function()
  local playerVeh = GetPlayersLastVehicle()
  ExecuteCommand( "raisecar")
  Citizen.Wait(1000)
  SetVehicleDoorOpen(playerVeh, 4, false, false)
  TaskStartScenarioInPlace(GetPlayerPed(-1), 'PROP_HUMAN_BUM_BIN', 0, true)
  QBCore.Functions.Progressbar("engine5", "Installing level 4 upgrade", math.random(16000, 18000), false, true, {}, {}, {}, {}, function()
    SetVehicleMod(playerVeh, 11, 0, true)
    Citizen.Wait(3500)
    SetVehicleDoorShut(playerVeh, 4, false)
  end, function()
    ClearPedTasksImmediately(GetPlayerPed(-1))
    ExecuteCommand( "lowercar")
  end)
end)

RegisterNetEvent('customcarmods-turbo:turboY')
AddEventHandler('customcarmods-turbo:turboY', function()
  local playerVeh = GetPlayersLastVehicle()
  SetVehicleDoorOpen(playerVeh, 4, false, false)
  TaskStartScenarioInPlace(GetPlayerPed(-1), 'PROP_HUMAN_BUM_BIN', 0, true)
  QBCore.Functions.Progressbar("turboY", "Installing Turbo", math.random(13000, 16000), false, true, {}, {}, {}, {}, function()
    ToggleVehicleMod(playerVeh, 18, true)
    Citizen.Wait(3000)
    SetVehicleDoorShut(playerVeh, 4, false)
  end, function()
    ClearPedTasksImmediately(GetPlayerPed(-1))
  end)
end)
--Brakes
RegisterNetEvent('customcarmods-brakes:brakes1')
AddEventHandler('customcarmods-brakes:brakes1', function()
  local playerVeh = GetPlayersLastVehicle()
  SetVehicleDoorOpen(playerVeh, 4, false, false)
  TaskStartScenarioInPlace(GetPlayerPed(-1), 'PROP_HUMAN_BUM_BIN', 0, true)
  QBCore.Functions.Progressbar("turboY", "Installing Basic Brakes ", math.random(13000, 16000), false, true, {}, {}, {}, {}, function()
    SetVehicleMod(playerVeh, 12, 2, true)
    SetVehicleDoorShut(playerVeh, 4, false)
  end, function()
    ClearPedTasksImmediately(GetPlayerPed(-1))
  end)
end)

RegisterNetEvent('customcarmods-brakes:brakes2')
AddEventHandler('customcarmods-brakes:brakes2', function()
  local playerVeh = GetPlayersLastVehicle()
  SetVehicleDoorOpen(playerVeh, 4, false, false)
  TaskStartScenarioInPlace(GetPlayerPed(-1), 'PROP_HUMAN_BUM_BIN', 0, true)
  QBCore.Functions.Progressbar("turboY", "Installing Lvl 1 Upgrade", math.random(13000, 16000), false, true, {}, {}, {}, {}, function()
    SetVehicleMod(playerVeh, 12, 2, true)
    SetVehicleDoorShut(playerVeh, 4, false)
  end, function()
    ClearPedTasksImmediately(GetPlayerPed(-1))
  end)
end)

RegisterNetEvent('customcarmods-brakes:brakes3')
AddEventHandler('customcarmods-brakes:brakes3', function()
  local playerVeh = GetPlayersLastVehicle()
  SetVehicleDoorOpen(playerVeh, 4, false, false)
  TaskStartScenarioInPlace(GetPlayerPed(-1), 'PROP_HUMAN_BUM_BIN', 0, true)
  QBCore.Functions.Progressbar("turboY", "Installing Lvl 2 Upgrade", math.random(13000, 16000), false, true, {}, {}, {}, {}, function()
    SetVehicleMod(playerVeh, 12, 2, true)
    SetVehicleDoorShut(playerVeh, 4, false)
  end, function()
    ClearPedTasksImmediately(GetPlayerPed(-1))
  end)
end)

RegisterNetEvent('customcarmods-brakes:brakes4')
AddEventHandler('customcarmods-brakes:brakes4', function()
  local playerVeh = GetPlayersLastVehicle()
  SetVehicleDoorOpen(playerVeh, 4, false, false)
  TaskStartScenarioInPlace(GetPlayerPed(-1), 'PROP_HUMAN_BUM_BIN', 0, true)
  QBCore.Functions.Progressbar("brakes4", "Installing Lvl 3 Upgrade", math.random(13000, 16000), false, true, {}, {}, {}, {}, function()
    SetVehicleMod(playerVeh, 12, 2, true)
    SetVehicleDoorShut(playerVeh, 4, false)
  end, function()
    ClearPedTasksImmediately(GetPlayerPed(-1))
  end)
end)

--Transmission
RegisterNetEvent('customcarmods-trans:trans1')
AddEventHandler('customcarmods-trans:trans1', function()
  local playerVeh = GetPlayersLastVehicle()
  SetVehicleDoorOpen(playerVeh, 4, false, false)
  TaskStartScenarioInPlace(GetPlayerPed(-1), 'PROP_HUMAN_BUM_BIN', 0, true)
  QBCore.Functions.Progressbar("trans1", "Installing basic Transmission", math.random(16000, 18000), false, true, {}, {}, {}, {}, function()
    SetVehicleMod(playerVeh, 13, -1, true)
    Citizen.Wait(3500)
    SetVehicleDoorShut(playerVeh, 4, false)
  end, function()
    ClearPedTasksImmediately(GetPlayerPed(-1))
  end)
end)

RegisterNetEvent('customcarmods-trans:trans2')
AddEventHandler('customcarmods-trans:trans2', function()
  local playerVeh = GetPlayersLastVehicle()
  SetVehicleDoorOpen(playerVeh, 4, false, false)
  TaskStartScenarioInPlace(GetPlayerPed(-1), 'PROP_HUMAN_BUM_BIN', 0, true)
  QBCore.Functions.Progressbar("trans2", "Installing Lvl 1 Upgrade", math.random(16000, 18000), false, true, {}, {}, {}, {}, function()
    SetVehicleMod(playerVeh, 13, -1, true)
    Citizen.Wait(3500)
    SetVehicleDoorShut(playerVeh, 4, false)
  end, function()
    ClearPedTasksImmediately(GetPlayerPed(-1))
  end)
end)

RegisterNetEvent('customcarmods-trans:trans3')
AddEventHandler('customcarmods-trans:trans3', function()
  local playerVeh = GetPlayersLastVehicle()
  SetVehicleDoorOpen(playerVeh, 4, false, false)
  TaskStartScenarioInPlace(GetPlayerPed(-1), 'PROP_HUMAN_BUM_BIN', 0, true)
  QBCore.Functions.Progressbar("trans3", "Installing Lvl 2 Upgrade", math.random(16000, 18000), false, true, {}, {}, {}, {}, function()
    SetVehicleMod(playerVeh, 13, -1, true)
    Citizen.Wait(3500)
    SetVehicleDoorShut(playerVeh, 4, false)
  end, function()
    ClearPedTasksImmediately(GetPlayerPed(-1))
  end)
end)

RegisterNetEvent('customcarmods-trans:trans4')
AddEventHandler('customcarmods-trans:trans4', function()
  local playerVeh = GetPlayersLastVehicle()
  SetVehicleDoorOpen(playerVeh, 4, false, false)
  TaskStartScenarioInPlace(GetPlayerPed(-1), 'PROP_HUMAN_BUM_BIN', 0, true)
  QBCore.Functions.Progressbar("trans4", "Installing Lvl 3 Upgrade", math.random(16000, 18000), false, true, {}, {}, {}, {}, function()
    SetVehicleMod(playerVeh, 13, -1, true)
    Citizen.Wait(3500)
    SetVehicleDoorShut(playerVeh, 4, false)
  end, function()
    ClearPedTasksImmediately(GetPlayerPed(-1))
  end)
end)

--Suspension
RegisterNetEvent('customcarmods-susp:susp1')
AddEventHandler('customcarmods-susp:susp1', function()
  local playerVeh = GetPlayersLastVehicle()
  SetVehicleDoorOpen(playerVeh, 4, false, false)
  TaskStartScenarioInPlace(GetPlayerPed(-1), 'PROP_HUMAN_BUM_BIN', 0, true)
  QBCore.Functions.Progressbar("susp1", "Installing Basic Upgrade", math.random(16000, 18000), false, true, {}, {}, {}, {}, function()
    SetVehicleMod(playerVeh, 15, -1, true)
    Citizen.Wait(3200)
    SetVehicleDoorShut(playerVeh, 4, false)
  end, function()
    ClearPedTasksImmediately(GetPlayerPed(-1))
  end)
end)

RegisterNetEvent('customcarmods-susp:susp2')
AddEventHandler('customcarmods-susp:susp2', function()
  local playerVeh = GetPlayersLastVehicle()
  SetVehicleDoorOpen(playerVeh, 4, false, false)
  TaskStartScenarioInPlace(GetPlayerPed(-1), 'PROP_HUMAN_BUM_BIN', 0, true)
  QBCore.Functions.Progressbar("susp2", "Installing Lvl 1 Upgrade", math.random(16000, 18000), false, true, {}, {}, {}, {}, function()
    SetVehicleMod(playerVeh, 15, -1, true)
    Citizen.Wait(3200)
    SetVehicleDoorShut(playerVeh, 4, false)
  end, function()
    ClearPedTasksImmediately(GetPlayerPed(-1))
  end)
end)

RegisterNetEvent('customcarmods-susp:susp3')
AddEventHandler('customcarmods-susp:susp3', function()
  local playerVeh = GetPlayersLastVehicle()
  SetVehicleDoorOpen(playerVeh, 4, false, false)
  TaskStartScenarioInPlace(GetPlayerPed(-1), 'PROP_HUMAN_BUM_BIN', 0, true)
  QBCore.Functions.Progressbar("susp3", "Installing Lvl 2 Upgrade", math.random(16000, 18000), false, true, {}, {}, {}, {}, function()
    SetVehicleMod(playerVeh, 15, -1, true)
    Citizen.Wait(3200)
    SetVehicleDoorShut(playerVeh, 4, false)
  end, function()
    ClearPedTasksImmediately(GetPlayerPed(-1))
  end)
end)

RegisterNetEvent('customcarmods-susp:susp4')
AddEventHandler('customcarmods-susp:susp4', function()
  local playerVeh = GetPlayersLastVehicle()
  SetVehicleDoorOpen(playerVeh, 4, false, false)
  TaskStartScenarioInPlace(GetPlayerPed(-1), 'PROP_HUMAN_BUM_BIN', 0, true)
  QBCore.Functions.Progressbar("susp4", "Installing Lvl 3 Upgrade", math.random(16000, 18000), false, true, {}, {}, {}, {}, function()
    SetVehicleMod(playerVeh, 15, -1, true)
    Citizen.Wait(3200)
    SetVehicleDoorShut(playerVeh, 4, false)
  end, function()
    ClearPedTasksImmediately(GetPlayerPed(-1))
  end)
end)

RegisterNetEvent('customcarmods-susp:susp5')
AddEventHandler('customcarmods-susp:susp5', function()
  local playerVeh = GetPlayersLastVehicle()
  SetVehicleDoorOpen(playerVeh, 4, false, false)
  TaskStartScenarioInPlace(GetPlayerPed(-1), 'PROP_HUMAN_BUM_BIN', 0, true)
  QBCore.Functions.Progressbar("susp5", "Installing Lvl 3 Upgrade", math.random(16000, 18000), false, true, {}, {}, {}, {}, function()
    SetVehicleMod(playerVeh, 15, 3, true)
    Citizen.Wait(3200)
    SetVehicleDoorShut(playerVeh, 4, false)
  end, function()
    ClearPedTasksImmediately(GetPlayerPed(-1))
  end)
end)

--Blindage
RegisterNetEvent('customcarmods-arm:arm1')
AddEventHandler('customcarmods-arm:arm1', function()
  local playerVeh = GetPlayersLastVehicle()
  SetVehicleDoorOpen(playerVeh, 4, false, false)
  TaskStartScenarioInPlace(GetPlayerPed(-1), 'WORLD_HUMAN_WELDING', 0, true)
  QBCore.Functions.Progressbar("arm1", "Installing Basic Car Armor", math.random(13000, 16000), false, true, {}, {}, {}, {}, function()
    SetVehicleMod(playerVeh, 16, -1, true)
    Citizen.Wait(15200)
    SetVehicleDoorShut(playerVeh, 4, false)
  end, function()
    ClearPedTasksImmediately(GetPlayerPed(-1))
  end)
end)

RegisterNetEvent('customcarmods-arm:arm2')
AddEventHandler('customcarmods-arm:arm2', function()
  local playerVeh = GetPlayersLastVehicle()
  SetVehicleDoorOpen(playerVeh, 4, false, false)
  TaskStartScenarioInPlace(GetPlayerPed(-1), 'WORLD_HUMAN_WELDING', 0, true)
  QBCore.Functions.Progressbar("arm2", "Installing Lvl 1 Upgrade", math.random(13000, 16000), false, true, {}, {}, {}, {}, function()
    SetVehicleMod(playerVeh, 16, 0, true)
    Citizen.Wait(3200)
    SetVehicleDoorShut(playerVeh, 4, false)
  end, function()
    ClearPedTasksImmediately(GetPlayerPed(-1))
  end)
end)

RegisterNetEvent('customcarmods-arm:arm3')
AddEventHandler('customcarmods-arm:arm3', function()
  local playerVeh = GetPlayersLastVehicle()
  SetVehicleDoorOpen(playerVeh, 4, false, false)
  TaskStartScenarioInPlace(GetPlayerPed(-1), 'WORLD_HUMAN_WELDING', 0, true)
  QBCore.Functions.Progressbar("arm3", "Installing Lvl 2 Upgrade", math.random(13000, 16000), false, true, {}, {}, {}, {}, function()
    SetVehicleMod(playerVeh, 16, 0, true)
    Citizen.Wait(3200)
    SetVehicleDoorShut(playerVeh, 4, false)
  end, function()
    ClearPedTasksImmediately(GetPlayerPed(-1))
  end)
end)

RegisterNetEvent('customcarmods-arm:arm4')
AddEventHandler('customcarmods-arm:arm4', function()
  local playerVeh = GetPlayersLastVehicle()
  SetVehicleDoorOpen(playerVeh, 4, false, false)
  TaskStartScenarioInPlace(GetPlayerPed(-1), 'WORLD_HUMAN_WELDING', 0, true)
  QBCore.Functions.Progressbar("arm4", "Installing Lvl 3 Upgrade", math.random(13000, 16000), false, true, {}, {}, {}, {}, function()
    SetVehicleMod(playerVeh, 16, 0, true)
    Citizen.Wait(3200)
    SetVehicleDoorShut(playerVeh, 4, false)
  end, function()
    ClearPedTasksImmediately(GetPlayerPed(-1))
  end)
end)

RegisterNetEvent('customcarmods-arm:arm5')
AddEventHandler('customcarmods-arm:arm5', function()
  local playerVeh = GetPlayersLastVehicle()
  SetVehicleDoorOpen(playerVeh, 4, false, false)
  TaskStartScenarioInPlace(GetPlayerPed(-1), 'WORLD_HUMAN_WELDING', 0, true)
  QBCore.Functions.Progressbar("arm5", "Installing Lvl 4 Upgrade", math.random(13000, 16000), false, true, {}, {}, {}, {}, function()
    SetVehicleMod(playerVeh, 16, 0, true)
    Citizen.Wait(3200)
    SetVehicleDoorShut(playerVeh, 4, false)
  end, function()
    ClearPedTasksImmediately(GetPlayerPed(-1))
  end)
end)

RegisterNetEvent('customcarmods-arm:arm6')
AddEventHandler('customcarmods-arm:arm6', function()
  local playerVeh = GetPlayersLastVehicle()
  SetVehicleDoorOpen(playerVeh, 4, false, false)
  TaskStartScenarioInPlace(GetPlayerPed(-1), 'WORLD_HUMAN_WELDING', 0, true)
  QBCore.Functions.Progressbar("arm6", "Installing Lvl 5 Upgrade", math.random(13000, 16000), false, true, {}, {}, {}, {}, function()
    SetVehicleMod(playerVeh, 16, 0, true)
    Citizen.Wait(3200)
    SetVehicleDoorShut(playerVeh, 4, false)
  end, function()
    ClearPedTasksImmediately(GetPlayerPed(-1))
  end)
end)

--Window Tint
RegisterNetEvent('customcarmods-win:win1')
AddEventHandler('customcarmods-win:win1', function()
  local playerVeh = GetPlayersLastVehicle()
  TaskStartScenarioInPlace(GetPlayerPed(-1), 'WORLD_HUMAN_MAID_CLEAN', 0, true)
  QBCore.Functions.Progressbar("win1", "Installing Basic Tint", math.random(16000, 18000), false, true, {}, {}, {}, {}, function()
    ToggleVehicleMod(playerVeh, 46, true)
    SetVehicleWindowTint(playerVeh, 1)
    Citizen.Wait(3200)
  end, function()
    ClearPedTasksImmediately(GetPlayerPed(-1))
  end)
end)

RegisterNetEvent('customcarmods-win:win2')
AddEventHandler('customcarmods-win:win2', function()
  local playerVeh = GetPlayersLastVehicle()
  TaskStartScenarioInPlace(GetPlayerPed(-1), 'WORLD_HUMAN_MAID_CLEAN', 0, true)
  QBCore.Functions.Progressbar("win2", "Installing Lvl 1 Upgrade", math.random(16000, 18000), false, true, {}, {}, {}, {}, function()
    ToggleVehicleMod(playerVeh, 46, true)
    SetVehicleWindowTint(playerVeh, 1)
    Citizen.Wait(3200)
  end, function()
    ClearPedTasksImmediately(GetPlayerPed(-1))
  end)
end)

RegisterNetEvent('customcarmods-win:win3')
AddEventHandler('customcarmods-win:win3', function()
  local playerVeh = GetPlayersLastVehicle()
  TaskStartScenarioInPlace(GetPlayerPed(-1), 'WORLD_HUMAN_MAID_CLEAN', 0, true)
  QBCore.Functions.Progressbar("trans3", "Installing Lvl 2 Upgrade", math.random(16000, 18000), false, true, {}, {}, {}, {}, function()
    ToggleVehicleMod(playerVeh, 46, true)
    SetVehicleWindowTint(playerVeh, 1)
    Citizen.Wait(3200)
  end, function()
    ClearPedTasksImmediately(GetPlayerPed(-1))
  end)
end)

RegisterNetEvent('customcarmods-win:win4')
AddEventHandler('customcarmods-win:win4', function()
  local playerVeh = GetPlayersLastVehicle()
  TaskStartScenarioInPlace(GetPlayerPed(-1), 'WORLD_HUMAN_MAID_CLEAN', 0, true)
  QBCore.Functions.Progressbar("trans3", "Installing Lvl 3 Upgrade", math.random(16000, 18000), false, true, {}, {}, {}, {}, function()
    ToggleVehicleMod(playerVeh, 46, true)
    SetVehicleWindowTint(playerVeh, 1)
    Citizen.Wait(3200)
  end, function()
    ClearPedTasksImmediately(GetPlayerPed(-1))
  end)
end)

RegisterNetEvent('qb-customcarmods:saveMods')
AddEventHandler('qb-customcarmods:saveMods', function()
	local vehicle = GetVehiclePedIsIn(PlayerPedId(), false)
	myCar = QBCore.Functions.GetVehicleProperties(vehicle)
	TriggerServerEvent('qb-customcarmods:refreshOwnedVehicle', myCar)
end)